### ISSUE TITLE
SSR breaks and it needs refactoring to Next 12

### ISSUE THREAD

**Issue by Seijinx** [telerik/kendo-react-nextjs#1]
NextJS has become a great first-choice solution for implementing Fullstack web project. Sadly this example is not up to date with the recent version of NextJS (12.0.8 at this time).

It would be greatly appreciated if you could provide an example that is working with SSR for this version of Next.

In this current state this example is pretty useless as it's raising error when Server-rendering. The only workaround at this point is using Dynamic import to prevent SSR (https://nextjs.org/docs/advanced-features/dynamic-import)

Thank you Telerik !

![image](https://user-images.githubusercontent.com/16969395/150654313-4287514d-91c7-4ca6-b159-98ea5f07e381.png)

**Comment by Seijinx** [comment]
Thanks Telerik for improving the last example using "app router" with Next 13 but sadly a dynamic import with "ssr" flag to "false" is still a problem for SEO heavy websites.

I get that time is a limited currency but knowing it's been nearly 2 years since my initial comment and that you're asking a pro license for each dev using it, its hardly conceivable on my end why we're still in this situation.

Our org will have to phase out kendo-react in the near future if SSR does not become a first-class citizen.

**Comment by WissamProgress** [comment]
Hi @Seijinx 
We are currently working on adding full support for the KendoReact components with NextJS and this update will be released in mid December.

Using dynamic with SSR set to false for the Grid is not necessary but we currently have it as a workaround since it was showing some warnings in development mode. You can import the Grid directly in `page.tsx` for example with the `use client` directive on top.

Nevertheless, these warnings will be all fixed in the December release.

If you have any additional concerns, please let me know.

**Comment by WissamProgress** [comment]
@Seijinx The KendoReact components are now all fully compatible with Next.js as of version 7.0.1

- https://www.telerik.com/kendo-react-ui/components/changelogs/ui-for-react/#v7.0.1
- https://www.telerik.com/kendo-react-ui/components/integration/nextjs/
- https://www.telerik.com/kendo-react-ui/components/getting-started/nextjs/

I will now close this issue, but feel free to let us know if you have any further question by adding it here, or by sending a support ticket.
